#!/bin/bash

function envup() {
    local arg=""
    local config_file=""
    for arg in "$@"; do
        for config_file in $(ls "$arg"); do
            if [[ -f "$config_file" ]]; then
                while read -r var val; do
                    var="$(echo "$var" | sed 's/ /_/g')"
                    export $var="$(echo "$val" | envsubst)"
                done <<< "$(cat "$config_file" | grep -v '^#.*' | perl -pe 's/(?<=[^\\])(\s*#.*)//g'| sed 's/\\#/#/g')"
            else
                >&2 echo "missing config file"
                exit 1
            fi
        done
    done
}

